// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace MyNamespace.NativeProvider
{
    [NativeProviderResourceType("nativeProvider:index:Organisation")]
    public partial class Organisation : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Id of the organisation created
        /// </summary>
        [Output("orgId")]
        public Output<int> OrgId { get; private set; } = null!;

        /// <summary>
        /// Name of organisation created
        /// </summary>
        [Output("orgName")]
        public Output<string> OrgName { get; private set; } = null!;


        /// <summary>
        /// Create a Organisation resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Organisation(string name, OrganisationArgs? args = null, CustomResourceOptions? options = null)
            : base("nativeProvider:index:Organisation", name, args ?? new OrganisationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Organisation(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nativeProvider:index:Organisation", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pierskarsenbarg/native-provider-demo",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Organisation resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Organisation Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Organisation(name, id, options);
        }
    }

    public sealed class OrganisationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the organisation
        /// </summary>
        [Input("orgName")]
        public Input<string>? OrgName { get; set; }

        public OrganisationArgs()
        {
        }
        public static new OrganisationArgs Empty => new OrganisationArgs();
    }
}
