name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-provider:
    name: Build Provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache-dependency-path: provider/go.sum

      - uses: arduino/setup-task@v2

      - uses: pulumi/actions@v6
        with:
          pulumi-version: "3.124.0"
          

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: pulumi/pulumictl

      - name: Build provider
        working-directory: provider
        run: task build_provider
